feat: Add webtransport component
multiformats/js-multiaddr pull request #271
Opened 2022-09-13 20:55 UTC by MarcoPolo

This adds the webtransport protocol here

2022-09-14 16:46 UTC, achingbrain requested changes
LGTM, just needs an ipv4 test alongside the ipv6 one.

2022-09-14 19:19 UTC, MarcoPolo commented on test/index.spec.ts
> +    const str = '/ip6/2001:8a0:7ac5:4201:3ac9:86ff:fe31:7095/udp/4001/quic/webtransport'
Honest question, does this matter? Is it possible to get parsing failure if an earlier protocol is different? My understanding is as far as this library is concerned it doesn't care if the multiaddr is valid or not. It just parses the multiaddr into parts.

2022-09-16 06:23 UTC, achingbrain commented on test/index.spec.ts
> +    const str = '/ip6/2001:8a0:7ac5:4201:3ac9:86ff:fe31:7095/udp/4001/quic/webtransport'
> Is it possible to get parsing failure if an earlier protocol is different?

It's hard to say for sure now without a test and impossible to say for the future.

IPv4 is likely to be the most common input so it seems reasonable to have a test that exercises it, which would also then be consistent with the other tests in the file.

2022-09-20 09:51 UTC, achingbrain approved these changes

2022-09-20 09:51 UTC, merged