fix: Rename webrtc-w3c to webrtc-private-to-private
multiformats/js-multiaddr pull request #314
Opened 2023-03-09 21:12 UTC by mxinden

We have decided to rename `webrtc-w3c` to `webrtc-private-to-private`. See rational in https://github.com/multiformats/multiaddr/pull/150/#issuecomment-1460912728.

No software has been released using `webrtc-w3c`, thus renaming is not a breaking change. Ignoring the automated `multiaddr` `v11.5.0` release.

See also https://github.com/multiformats/js-multiaddr/pull/309 that introduced `webrtc-w3c`.

2023-03-09 21:13 UTC, mxinden commented
> No software has been released using `webrtc-w3c`, thus renaming is not a breaking change. Ignoring the automated `multiaddr` `v11.5.0` release.

@achingbrain is the assumption correct that this does not pose any issues even though there has been an automated release,namely `v11.5.0`, with `webrtc-w3c`?

2023-03-13 09:52 UTC, mxinden commented
Friendly ping @achingbrain, @MarcoPolo and @marten-seemann.

2023-03-13 17:18 UTC, MarcoPolo commented
Are we actually using this anywhere? Why is it a breaking change?

2023-03-13 17:25 UTC, achingbrain commented
It's breaking because methods that previously accepted `"webrtc-w3c"` as input or returned it will now accept/return `"webrtc-private-to-private"` instead.

2023-03-13 17:27 UTC, MarcoPolo commented
Yes, it's technically a breaking change. I see that. Is there anything that is using this that will be affected?

2023-03-17 07:04 UTC, achingbrain requested changes
In https://github.com/multiformats/multiaddr/pull/152/files we decided that the browser-to-server version would be called `webrtc-direct` and the browser-to-browser version would just be `webrtc`

2023-03-17 07:04 UTC, achingbrain commented on src/protocols-table.ts
>    [280, 0, 'webrtc'],
```suggestion
  [280, 0, 'webrtc-direct'],
```

2023-03-17 07:04 UTC, achingbrain commented on src/protocols-table.ts
> +  [281, 0, 'webrtc-private-to-private'],
```suggestion
  [281, 0, 'webrtc'],
```

2023-03-17 07:05 UTC, achingbrain approved these changes

2023-03-17 07:14 UTC, merged